export enum ErrorCode {
  // Auth
  INVALID_CREDENTIALS = 'AUTH_001',
  TOKEN_EXPIRED = 'AUTH_002',
  TOKEN_BLACKLISTED = 'AUTH_003',
  REFRESH_TOKEN_EXPIRED = 'AUTH_004',
  REFRESH_TOKEN_REUSE_DETECTED = 'AUTH_005',
  INSUFFICIENT_PERMISSIONS = 'AUTH_006',
  ACCOUNT_DISABLED = 'AUTH_007',

  // Users
  USER_NOT_FOUND = 'USER_001',
  USER_EMAIL_TAKEN = 'USER_002',
  USER_CANNOT_DELETE_SELF = 'USER_003',

  // Organisations
  ORGANISATION_NOT_FOUND = 'ORG_001',
  ORGANISATION_CODE_TAKEN = 'ORG_002',
  ORGANISATION_NAME_TAKEN = 'ORG_003',

  // Directions
  DIRECTION_NOT_FOUND = 'DIR_001',
  DIRECTION_CODE_TAKEN = 'DIR_002',
  DIRECTION_NAME_TAKEN = 'DIR_003',

  // Départements
  DEPARTEMENT_NOT_FOUND = 'DEP_001',
  DEPARTEMENT_CODE_TAKEN = 'DEP_002',
  DEPARTEMENT_NAME_TAKEN = 'DEP_003',

  // Unités
  UNITE_NOT_FOUND = 'UNI_001',
  UNITE_CODE_TAKEN = 'UNI_002',
  UNITE_NAME_TAKEN = 'UNI_003',

  // Programmes
  PROGRAMME_NOT_FOUND = 'PRG_001',
  PROGRAMME_CODE_TAKEN = 'PRG_002',
  PROGRAMME_NAME_TAKEN = 'PRG_003',

  // Projects
  PROJECT_NOT_FOUND = 'PROJ_001',
  PROJECT_CODE_TAKEN = 'PROJ_002',
  PROJECT_ACCESS_DENIED = 'PROJ_003',
  PROJECT_ALREADY_CLOSED = 'PROJ_004',

  // Project Members
  PROJECT_MEMBER_NOT_FOUND = 'PMEM_001',
  PROJECT_MEMBER_ALREADY_EXISTS = 'PMEM_002',

  // Gouvernance
  GOUVERNANCE_NOT_FOUND = 'GOUV_001',

  // Logframe Objectives
  LOGFRAME_OBJECTIVE_NOT_FOUND = 'LOGF_001',
  LOGFRAME_OBJECTIVE_PARENT_NOT_FOUND = 'LOGF_002',

  // Logframe Indicators
  LOGFRAME_INDICATOR_NOT_FOUND = 'LOGI_001',

  // WBS
  WBS_NODE_NOT_FOUND = 'WBS_001',
  WBS_INVALID_HIERARCHY = 'WBS_002',

  // PTBA
  PTBA_ACTIVITE_NOT_FOUND = 'PTBA_001',
  PTBA_INVALID_LINK = 'PTBA_002',

  // Journal Opérations
  JOURNAL_OPERATION_NOT_FOUND = 'JOUR_001',

  // Funding Sources
  FUNDING_SOURCE_NOT_FOUND = 'FUND_001',

  // Disbursements
  DISBURSEMENT_NOT_FOUND = 'DISB_001',
  DISBURSEMENT_COHERENCE_VIOLATION = 'DISB_002',

  // Budget
  BUDGET_NOT_FOUND = 'BUDG_001',
  BUDGET_LOCKED = 'BUDG_002',
  BUDGET_VERSION_NOT_FOUND = 'BUDG_003',
  BUDGET_COHERENCE_VIOLATION = 'BUDG_004',
  BUDGET_LIGNE_NOT_FOUND = 'BUDG_005',

  // Risks
  RISK_NOT_FOUND = 'RISK_001',

  // Livrables
  LIVRABLE_NOT_FOUND = 'LIVR_001',
  LIVRABLE_INVALID_STATUS_TRANSITION = 'LIVR_002',

  // EVM
  EVM_SNAPSHOT_NOT_FOUND = 'EVM_001',
  EVM_SNAPSHOT_PERIODE_EXISTS = 'EVM_002',

  // Documents
  DOCUMENT_NOT_FOUND = 'DOC_001',
  DOCUMENT_VERSION_NOT_FOUND = 'DOC_002',

  // Uploads
  UPLOAD_FILE_TOO_LARGE = 'UPL_001',
  UPLOAD_MIME_NOT_ALLOWED = 'UPL_002',
  UPLOAD_MAGIC_BYTES_MISMATCH = 'UPL_003',
  UPLOAD_MALWARE_DETECTED = 'UPL_004',
  UPLOAD_NOT_FOUND = 'UPL_005',

  // Reports
  REPORT_NOT_FOUND = 'RPT_001',
  REPORT_ALREADY_PROCESSING = 'RPT_002',

  // PPM
  PPM_MARCHE_NOT_FOUND = 'PPM_001',
  PPM_MARCHE_CODE_TAKEN = 'PPM_002',
  PPM_ETAPE_NOT_FOUND = 'PPM_003',

  // Contracts
  CONTRACT_NOT_FOUND = 'CTR_001',
  CONTRACT_COHERENCE_VIOLATION = 'CTR_002',

  // Comments
  COMMENT_NOT_FOUND = 'CMT_001',
  COMMENT_ACCESS_DENIED = 'CMT_002',

  // Notifications
  NOTIFICATION_NOT_FOUND = 'NOTIF_001',

  // History
  HISTORY_NOT_FOUND = 'HIST_001',

  // Generic
  VALIDATION_ERROR = 'GEN_001',
  RESOURCE_NOT_FOUND = 'GEN_002',
  INTERNAL_SERVER_ERROR = 'GEN_003',
  CONFLICT = 'GEN_004',
  UNPROCESSABLE_ENTITY = 'GEN_005',
}
